### ISSUE TITLE
Audio playback crashes with 'ALSA via PortAudio' output

### ISSUE THREAD

**Issue by newbluemoon** [praat/praat#682]
Hi!

I’m on x86_64 Linux, loading a sound file via ‘Read from file...’. Shortly after hitting the play button praat crashes when using the 'ALSA via PortAudio' output. PulseAudio works fine. Here’s a gdb backtrace:

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff44a1ffd in __GI_abort () at abort.c:90
#2  0x00007ffff4499147 in __assert_fail_base (fmt=<optimized out>, assertion=assertion@entry=0x555556654bde "ret == self->nfds", file=file@entry=0x555556654b65 "pa_linux_alsa.c", 
    line=line@entry=3639, function=function@entry=0x555556655120 <__PRETTY_FUNCTION__.12817> "PaAlsaStreamComponent_BeginPolling") at assert.c:92
#3  0x00007ffff44991f2 in __GI___assert_fail (assertion=0x555556654bde "ret == self->nfds", file=0x555556654b65 "pa_linux_alsa.c", line=3639, 
    function=0x555556655120 <__PRETTY_FUNCTION__.12817> "PaAlsaStreamComponent_BeginPolling") at assert.c:101
#4  0x0000555555d3ec23 in PaAlsaStreamComponent_BeginPolling () at pa_linux_alsa.c:3639
#5  0x0000555555d4468b in PaAlsaStreamComponent_BeginPolling () at pa_linux_alsa.c:3897
#6  PaAlsaStream_WaitForFrames () at pa_linux_alsa.c:3800
#7  0x0000555555d44dc0 in CallbackThreadFunc () at pa_linux_alsa.c:4251
#8  0x00007ffff5191568 in start_thread (arg=0x7fffe17fa700) at pthread_create.c:465
#9  0x00007ffff456052f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I’m using Void Linux which is a rolling release distro. Could it be that the bundled PortAudio is too old (READ_ME.TXT says February 2014)?

**Comment by newbluemoon** [comment]
This issue seems to be resolved with 6.0.45. Thanks! :)
